// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cov_cal_long
Rcpp::List cov_cal_long(arma::colvec beta, arma::colvec M, arma::colvec rho01, arma::colvec rho02, arma::mat XS, arma::colvec dati, arma::colvec datj);
RcppExport SEXP _tPAUC_cov_cal_long(SEXP betaSEXP, SEXP MSEXP, SEXP rho01SEXP, SEXP rho02SEXP, SEXP XSSEXP, SEXP datiSEXP, SEXP datjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type rho01(rho01SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type rho02(rho02SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type XS(XSSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type dati(datiSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type datj(datjSEXP);
    rcpp_result_gen = Rcpp::wrap(cov_cal_long(beta, M, rho01, rho02, XS, dati, datj));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tPAUC_cov_cal_long", (DL_FUNC) &_tPAUC_cov_cal_long, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_tPAUC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
